import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Pencil, Pill, Plus, Search } from 'lucide-react';
import { supabase } from '../lib/supabase';

type AdminRole='owner'|'admin'|'editor'|'reviewer';
type ContentStatus='draft'|'review'|'approved'|'published'|'rejected'|'archived';
type Profile={id:string;role:AdminRole;is_active:boolean};
type Row={id:string;slug:string;title_ar:string|null;title_en:string|null;status:ContentStatus;version:number};
const STATUS:Record<ContentStatus,string>={draft:'مسودة',review:'بانتظار المراجعة',approved:'معتمد',published:'منشور',rejected:'يحتاج تعديل',archived:'مؤرشف'};

export default function AdminDrugHub(){
 const[profile,setProfile]=useState<Profile|null>(null);const[items,setItems]=useState<Row[]>([]);const[query,setQuery]=useState('');const[ready,setReady]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const load=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace('/admin');return;}const{data:pd,error:pe}=await supabase.from('admin_profiles').select('id,role,is_active').eq('id',session.user.id).maybeSingle();if(cancelled)return;if(pe||!pd?.is_active){setError('هذا الحساب لا يملك صلاحية إدارة دليلي.');setReady(true);return;}setProfile(pd as Profile);const{data,error:listError}=await supabase.from('content_items').select('id,slug,title_ar,title_en,status,version').eq('content_type','drug').order('title_ar',{ascending:true});if(listError)setError(listError.message);setItems((data??[])as Row[]);setReady(true);};void load();return()=>{cancelled=true;};},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return items;return items.filter((item)=>[item.slug,item.title_ar??'',item.title_en??'',STATUS[item.status]].some((x)=>x.toLowerCase().includes(q)));},[items,query]);
 if(!ready)return <div className="flex min-h-screen items-center justify-center bg-[#07182c] text-sm font-bold text-white">جاري تحميل الأدوية…</div>;
 if(error||!profile)return <div dir="rtl" className="flex min-h-screen items-center justify-center bg-[#07182c] p-5"><div className="max-w-md rounded-3xl bg-white p-6 text-center"><p className="font-bold text-red-700">{error||'غير مخوّل.'}</p><a href="/admin" className="mt-4 inline-block rounded-xl bg-[#173a63] px-4 py-3 font-bold text-white">الرجوع</a></div></div>;
 const canEdit=profile.role==='owner'||profile.role==='admin'||profile.role==='editor';
 return <div dir="rtl" className="min-h-screen overflow-x-hidden bg-[#eef3f8] text-[#24313f]"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#07182c] text-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-3 px-4 py-4"><a href="/admin" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white/10" aria-label="الرجوع"><ArrowRight size={20}/></a><div className="min-w-0 text-right"><p className="text-xs font-bold text-[#d9a441]">دليلي — إدارة المحتوى</p><h1 className="truncate text-lg font-black">الأدوية</h1></div></div></header><main className="mx-auto max-w-5xl space-y-4 px-3 py-4 sm:px-6 sm:py-6"><section className="rounded-2xl bg-white p-3 shadow-sm ring-1 ring-slate-200/70"><div className="grid gap-2 sm:grid-cols-[auto_1fr]">{canEdit&&<a href="/admin/drugs" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[#173a63] px-4 py-3 text-sm font-black text-white"><Plus size={18}/> إضافة دواء جديد</a>}<div className="relative"><Search size={18} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="بحث باسم الدواء…" className="min-h-12 w-full rounded-2xl border border-[#d9e6f2] bg-[#f8fbfd] pr-10 pl-4 text-base outline-none focus:border-[#2f69a8]"/></div></div><div className="mt-3 text-xs font-bold text-slate-500">{filtered.length} عنصر</div></section>{filtered.length===0?<div className="rounded-2xl border border-dashed border-[#b9cee2] bg-white p-8 text-center"><Pill className="mx-auto mb-3 text-[#2f69a8]"/><p className="text-sm font-bold text-slate-500">لا توجد أدوية مطابقة.</p></div>:<div className="grid gap-2 sm:grid-cols-2">{filtered.map((item)=><article key={item.id} className="min-w-0 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200/70"><div className="flex items-start justify-between gap-3"><span className="shrink-0 rounded-full bg-[#eef3f8] px-2.5 py-1 text-[11px] font-bold text-[#173a63]">{STATUS[item.status]}</span><div className="min-w-0 text-right"><h2 className="break-words font-black text-[#0a2037]">{item.title_ar||item.title_en||item.slug}</h2><p dir="ltr" className="mt-1 truncate text-xs text-slate-400">{item.title_en||item.slug} · v{item.version}</p></div></div>{canEdit&&<a href={`/admin/drugs?id=${encodeURIComponent(item.id)}`} className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#f8fbfd] px-3 py-2 text-xs font-black text-[#173a63] ring-1 ring-[#d9e6f2]"><Pencil size={14}/> تعديل</a>}</article>)}</div>}</main></div>;
}
